### ISSUE TITLE
segfault when applying demonset

### ISSUE THREAD

**Issue by 1highmax** [collabora/k8s-socketcan#3]
Hi guys,
I get the following segfault on a fresh machine with microk8s newly installed. I played around in minikube too, but with the same error.

Following the tutorial:
```
microk8s kubectl apply -f https://raw.githubusercontent.com/Collabora/k8s-socketcan/main/k8s-socketcan-daemonset.yaml
```
and then checking the logs shows a segfault. Does anybody have an idea? The logs of the init look good.

```
$ microk8s kubectl logs k8s-socketcan-k66h9 init
Succesfully installed and loaded the vcan kernel module
mknod: /var/run/k8s-socketcan/fakedev: File exists
Found containerd socket in /root/var/snap/microk8s/common/run/containerd.sock
```
but the logs of the socketcan fail.

``` 
$ microk8s kubectl logs k8s-socketcan-k66h9 k8s-socketcan 
I0113 22:16:20.817409   41014 plugin.go:141] vcan: Registration for endpoint k8s.collabora.com_vcan
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0xbc2c1c]

goroutine 72 [running]:
k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1.(*DevicePluginOptions).MarshalToSizedBuffer(...)
	/home/runner/go/pkg/mod/k8s.io/kubelet@v0.23.2/pkg/apis/deviceplugin/v1beta1/api.pb.go:1546
k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1.(*DevicePluginOptions).Marshal(0x0, 0xd6d140, 0x0, 0x7fb064ca0058, 0x0, 0x1)
	/home/runner/go/pkg/mod/k8s.io/kubelet@v0.23.2/pkg/apis/deviceplugin/v1beta1/api.pb.go:1529 +0x7c
google.golang.org/protobuf/internal/impl.legacyMarshal(0xead638, 0xc000782080, 0x0, 0x0, 0x0, 0x0, 0xd6d140, 0x7fb064daf240, 0xd6d140, 0x0, ...)
	/home/runner/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/legacy_message.go:404 +0xb3
google.golang.org/protobuf/proto.MarshalOptions.marshal(0xc000000001, 0x0, 0x0, 0x0, 0xead638, 0xc000782080, 0xc000782080, 0xead638, 0xc000782080, 0xd6d140, ...)
	/home/runner/go/pkg/mod/google.golang.org/protobuf@v1.27.1/proto/encode.go:163 +0x25e
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x1, 0x0, 0x0, 0x0, 0xe8eaa0, 0xc000782080, 0x0, 0x7fb064ca0008, 0x20300000000000, 0x7fb0652ebfff, ...)
	/home/runner/go/pkg/mod/google.golang.org/protobuf@v1.27.1/proto/encode.go:122 +0x98
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x7fb064ca0008, 0x0, 0x400, 0x400, 0x10, 0x7fb065128500, 0x7fb0652ebfff, ...)
	/home/runner/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/wire.go:40 +0xdc
github.com/golang/protobuf/proto.Marshal(...)
	/home/runner/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal(0xd6d140, 0x0, 0x10, 0x1, 0x40a4bf, 0xc00001e000, 0xcc09e0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/encoding/proto/proto.go:45 +0x6d
google.golang.org/grpc.encode(0x7fb064d6c338, 0x1380698, 0xd6d140, 0x0, 0x1380698, 0x7fb064cdfeb8, 0x0, 0xd30c60, 0x7fb064dad858)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/rpc_util.go:594 +0x52
google.golang.org/grpc.(*Server).sendResponse(0xc000126000, 0xeaa638, 0xc0005bc180, 0xc0005e8000, 0xd6d140, 0x0, 0x0, 0x0, 0xc000788000, 0x0, ...)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1082 +0x91
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000126000, 0xeaa638, 0xc0005bc180, 0xc0005e8000, 0xc00010a240, 0x1340b40, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1332 +0x625
google.golang.org/grpc.(*Server).handleStream(0xc000126000, 0xeaa638, 0xc0005bc180, 0xc0005e8000, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000580060, 0xc000126000, 0xeaa638, 0xc0005bc180, 0xc0005e8000)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd

```

**Comment by jpc** [comment]
Hey,

Thanks for the report. I tested it just now and it still works correctly for me on a fresh install of `microk8s` on my Mac (arm64). Could you please provide some more info about your setup so I could try to reproduce it? What architecture and Linux distribution are you running?

**Comment by 1highmax** [comment]
Hi thanks for the quick reply.

I have tried on both native and fresh VM installs of ubuntu 22.04.

```
uname -a
Linux osboxes 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

microk8s kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.0


snap info microk8s | grep installed
installed:               v1.26.0             (4390) 176MB classic

```

I have tried to change the following line to not return nil, which would remove the segfault:
![image](https://user-images.githubusercontent.com/21125030/212644350-dff55d2f-ba85-421f-8fde-2c1ca7e14d53.png)

However there are still no can networks available for the ...-example pod.
![image](https://user-images.githubusercontent.com/21125030/212643857-e50472a6-5af4-472d-b8fc-555a4d91ee51.png)


Appreciate your help.

**Comment by jpc** [comment]
Hi, I've applied your patch and it fixed the segfault, thanks a lot for fixing it. It's interesting that the bug was architecture dependent (it worked correctly without the patch on arm64 but crashed on arm64).

After applying your patch the demo now works for me on:
```
Linux ubuntu-22-04-cpu-4v-fin1 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
It's the same as your setup only with `Ubuntu 22.04.1 LTS`.

I've added a DaemonSet yaml with debugging output enabled. Could you try to apply it:
```
microk8s kubectl apply -f https://raw.githubusercontent.com/collabora/k8s-socketcan/main/k8s-socketcan-daemonset-debug.yaml
```
and check it's logs:
```
microk8s kubectl logs -f -l name=k8s-socketcan -c k8s-socketcan
```
?

You many need to delete and re-apply the client Pod to force it to talk to the restarted daemon:
```
microk8s kubectl delete -f https://raw.githubusercontent.com/Collabora/k8s-socketcan/main/k8s-socketcan-client-example.yaml
microk8s kubectl apply -f https://raw.githubusercontent.com/Collabora/k8s-socketcan/main/k8s-socketcan-client-example.yaml
```

**Comment by 1highmax** [comment]
Hi, the remaining issue was fixed with another `microk8s reset` on my side.
Thanks for the help and have a nice evening.

**Comment by jpc** [comment]
That's great to hear! Once again thanks a lot for the bug report and your patch. Also good luck with your CAN project. :)
