### ISSUE TITLE
Segfault on Raspberry Pi

### ISSUE THREAD

**Issue by minecraft2048** [collabora/k8s-socketcan#4]
I'm using k3s to run my kubernetes cluster on RPi4s ,and set `can0` in `SOCKETCAN_DEVICES`
```
        env:
        - name: SOCKETCAN_DEVICES
          value: "can0"
```
and my k8s-socketcan pods are not starting, looking at the log we got a segfault:
```
byakuya@ifrit-hpc ~/w/D/k8s-socketcan (main)> kubectl logs k8s-socketcan-q7bgj 
Defaulted container "k8s-socketcan" out of: k8s-socketcan, init (init)
I0502 01:50:35.541082    4997 plugin.go:141] vcan: Registration for endpoint k8s.collabora.com_vcan
I0502 01:50:35.546883    4997 plugin.go:141] can0: Registration for endpoint k8s.collabora.com_can0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x6a274c]

goroutine 56 [running]:
k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1.(*DevicePluginOptions).MarshalToSizedBuffer(...)
        /home/runner/go/pkg/mod/k8s.io/kubelet@v0.23.2/pkg/apis/deviceplugin/v1beta1/api.pb.go:1546
k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1.(*DevicePluginOptions).Marshal(0x0, 0x847140, 0x0, 0x7f6ceeacf8, 0x0, 0x9fb01)
        /home/runner/go/pkg/mod/k8s.io/kubelet@v0.23.2/pkg/apis/deviceplugin/v1beta1/api.pb.go:1529 +0x6c
google.golang.org/protobuf/internal/impl.legacyMarshal(0x987498, 0x40003ae2d0, 0x0, 0x0, 0x0, 0x0, 0x847140, 0x0, 0x4000654808, 0x3bb348, ...)
        /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/legacy_message.go:404 +0x8c
google.golang.org/protobuf/proto.MarshalOptions.marshal(0x4000000001, 0x0, 0x0, 0x0, 0x987498, 0x40003ae2d0, 0x40003ae2d0, 0x987498, 0x40003ae2d0, 0x5, ...)
        /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.27.1/proto/encode.go:163 +0x19c
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x1, 0x0, 0x0, 0x0, 0x968758, 0x40003ae2d0, 0x847140, 0x7f6ceeaca8, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.27.1/proto/encode.go:122 +0x78
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x7f6ceeaca8, 0x0, 0x0, 0x0, 0x7f6ceeabd8, 0x40006549f8, 0x435a48, ...)
        /home/runner/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/wire.go:40 +0x90
github.com/golang/protobuf/proto.Marshal(...)
        /home/runner/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal(0x847140, 0x0, 0x7c1780, 0x7f6cf6e0f8, 0x4000654a48, 0x1a030, 0x400001e000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/encoding/proto/proto.go:45 +0x54
google.golang.org/grpc.encode(0x7f6cf6e0f8, 0xe56438, 0x847140, 0x0, 0xe56438, 0x1c748, 0x80ad20, 0x7f6cfd9818, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/rpc_util.go:594 +0x44
google.golang.org/grpc.(*Server).sendResponse(0x40000f1500, 0x984518, 0x400038b380, 0x4000132480, 0x847140, 0x0, 0x0, 0x0, 0x400013c21c, 0x0, ...)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1082 +0x5c
google.golang.org/grpc.(*Server).processUnaryRPC(0x40000f1500, 0x984518, 0x400038b380, 0x4000132480, 0x400042c060, 0xe16920, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1332 +0x4a0
google.golang.org/grpc.(*Server).handleStream(0x40000f1500, 0x984518, 0x400038b380, 0x4000132480, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0xa70
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x400039e120, 0x40000f1500, 0x984518, 0x400038b380, 0x4000132480)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x1f8
```

The commit https://github.com/collabora/k8s-socketcan/commit/60bb7312be93b74cd526a0b889cb94cc87cc21e5 might already fix this, but I'm not sure whether `ghcr.io/collabora/k8s-socketcan:latest` have that commit or not

**Comment by minecraft2048** [comment]
Found the problem, commit 60bb731 only fixes it for the virtual CAN interface, not for physical CAN interface
Pull request https://github.com/collabora/k8s-socketcan/pull/5 fixes this

**Comment by jpc** [comment]
Thanks a lot for debugging this and fixing the issue.
